#pragma once
#include <vector>

#include <PxPhysicsAPI.h>

using namespace physx;


enum DriveMode
{
	eDRIVE_MODE_ACCEL_FORWARDS = 0,
	eDRIVE_MODE_ACCEL_REVERSE,
	eDRIVE_MODE_HARD_TURN_LEFT,
	eDRIVE_MODE_HANDBRAKE_TURN_LEFT,
	eDRIVE_MODE_HARD_TURN_RIGHT,
	eDRIVE_MODE_HANDBRAKE_TURN_RIGHT,
	eDRIVE_MODE_BRAKE,
	eDRIVE_MODE_NONE
};

enum ActiveGroup
{
	PLAYERGROUP1 = (1 << 0),
	PLAYERGROUP2 = (1 << 1),
	PLAYERGROUP3 = (1 << 2),
	PLAYERGROUP4 = (1 << 3)
};

